PesKit/PesKit/Areas/PestKitAdmin/ViewModels/Tag/CreateUpdateTagVM.cs
using PesKit.Models;
using System.ComponentModel.DataAnnotations;

namespace PesKit.Areas.PestKitAdmin.ViewModels
{
    public class CreateUpdateTagVM
    {
        [Required(ErrorMessage = "Title must be entered mutled")]
        [MaxLength(25, ErrorMessage = "It should not exceed 25 characters")]
        public string Name { get; set; }
        public List<BlogTag>? BlogTags { get; set; }
    }
}

PesKit/PesKit/Models/Tag.cs
namespace PesKit.Models
{
    public class Tag
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<BlogTag>? BlogTags { get; set; }
    }
}

PesKit/PesKit/Areas/PestKitAdmin/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PesKit.Areas.PestKitAdmin.ViewModels;
using PesKit.DAL;
using PesKit.Models;

namespace PesKit.Areas.PestKitAdmin.Controllers
{
    [Area("PestKitAdmin")]
   
   public class TagController : Controller
    {
        private readonly AppDbContext _context;

        public TagController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Tag> tags = await _context.Tags.Include(c => c.BlogTags).ThenInclude(c => c.Blog).ToListAsync();
            return View(tags);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateUpdateTagVM tagVM)
        {
            if (!ModelState.IsValid) { return View(tagVM); }
            bool result = _context.Tags.Any(t => t.Name.Trim().ToLower() == tagVM.Name.Trim().ToLower());
            if (result)
            {
                ModelState.AddModelError("Name", "A Tag is available");
                return View();
            }
            Tag tag = new Tag { Name = tagVM.Name };

            _context.Tags.Add(tag);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) { return BadRequest(); }
            Tag tag = await _context.Tags.FirstOrDefaultAsync(t => t.Id == id);
            if (tag == null) { return NotFound(); }

            _context.Tags.Remove(tag);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Details(int id)
        {
            if (id <= 0) { return BadRequest(); }
            Tag tag = _context.Tags.Include(c => c.BlogTags).ThenInclude(c => c.Blog).FirstOrDefault(c => c.Id == id);
            if (tag == null) { return NotFound(); }
            return View(tag);
        }

        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) { return BadRequest(); }
            Tag tag = await _context.Tags.FirstOrDefaultAsync(c => c.Id == id);
            if (tag == null) { return NotFound(); }
            CreateUpdateTagVM tagVM = new CreateUpdateTagVM { Name = tag.Name };

            return View(tagVM);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, CreateUpdateTagVM tagVM)
        {
            if (!ModelState.IsValid) { return View(tagVM); };
            Tag exist = await _context.Tags.FirstOrDefaultAsync(c => c.Id == id);
            if (exist == null) { return NotFound(); };
            bool result = await _context.Tags.AnyAsync(c => c.Name.Trim().ToLower() == exist.Name.Trim().ToLower() && c.Id != id);
            if (result)
            {
                ModelState.AddModelError("Name", "A Tag is available");
                return View(exist);
            }
            exist.Name = tagVM.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

PesKit/PesKit/Areas/PestKitAdmin/Views/Tag/Create.cshtml
@model CreateUpdateTagVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Tag</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a class="btn btn-light" asp-action="Index" asp-controller="Tag">Cancel</a>
            </form>
        </div>
    </div>
</div>

PesKit/PesKit/Areas/PestKitAdmin/Views/Tag/Details.cshtml
@model Tag


<div class="container">
    <h3 class="fw-bold m-3">@Model.Name Blogs</h3>
    <h4 class="fw-normal mx-5 my-3">Blogs Count: @Model.BlogTags.Count</h4>
</div>
<div class="card-group w-25">
    @foreach (BlogTag blog in Model.BlogTags)
    {
        <div class="">
            <img src="~/img//@blog.Blog.ImgUrl"
                 alt="@blog.Blog.Title">
            <div class="card-body">
                <h5 class="card-title text-white">Title: @blog.Blog.Title</h5>
                <p class="card-text">Description: @blog.Blog.Description</p
                <p class="card-text">Comment count: @blog.Blog.CommentCount</p>
                <p class="card-text">Date: @blog.Blog.DateTime</p>
            </div>
        </div>
    }
</div>

PesKit/PesKit/Areas/PestKitAdmin/Views/Tag/Index.cshtml
@model List<Tag>
@{
    int count = 0;
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Tags table</h4>
            <a asp-controller="Tag" asp-action="Create" class="btn btn-warning fw-bold fs-6 text-white">Create Tag</a>
            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                NO
                            </th>
                            <th>
                                Title
                            </th>
                            <th>
                                Blogs Count
                            </th>
                            <th>
                                Settings
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Tag tag in Model)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                </td>
                                <td>
                                    @tag.Name
                                </td>
                                <td>
                                    @tag.BlogTags.Count
                                </td>
                                <td>
                                    <a asp-action="Update" asp-controller="Tag" asp-route-id="@tag.Id" class="btn btn-primary btn-info">
                                        <i class="mdi mdi-pencil"></i>
                                    </a>
                                    <a asp-action="Delete" asp-controller="Tag" asp-route-id="@tag.Id" class="btn btn-danger btn-info">
                                        <i class="mdi mdi-delete"></i>
                                    </a>
                                    <a asp-action="Details" asp-controller="Tag" asp-route-id="@tag.Id" class="btn btn-primary">
                                        <i class="mdi mdi-open-in-new"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

PesKit/PesKit/Areas/PestKitAdmin/Views/Tag/Update.cshtml
@model CreateUpdateTagVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Tag</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a class="btn btn-light" asp-action="Index" asp-controller="Tag">Cancel</a>
            </form>
        </div>
    </div>
</div>